server:
  port: 9001
spring:
  application:
    name: community_base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community_base?useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true